import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  EN: {
    app_title: "NETRA-AI - Police Intelligence Suite",
    commander_panel: "COMMANDER KESHAV HQ PANEL",
    officer_workspace: "TACTICAL OFFICER WORKSPACE",
    dashboard: "Main Investigation Dashboard",
    new_case_file: "NEW CASE FILE",
    search_cases_placeholder: "Search 50+ Case Files by ID, Title, Suspect or Police Station...",
    kpi_total: "Total Cases Registered",
    kpi_solved: "Case Solved Rate",
    kpi_pending: "Active Pending Cases",
    kpi_efficiency: "Investigation Efficiency",
    priority_critical: "CRITICAL",
    priority_high: "HIGH",
    priority_medium: "MEDIUM",
    status_pending: "IN PROGRESS / PENDING",
    status_completed: "SOLVED / COMPLETED",
    evidence_grid_title: "Multi-Modal Evidence Ingestion Grid",
    evidence_path_restricted: "Path strictly locked to: C:\\Users\\Keshav Kumawat\\Desktop\\sih 2026",
    batch_scan_btn: "BATCH SCAN ALL EVIDENCE (PARALLEL AI PIPELINE)",
    graph_title: "Neo4j Live Force Graph & Intelligence Matrix",
    geospatial_title: "Live Suspect GPS Intercept Telemetry",
    xai_reasoning: "XAI Explainability Rationale Matrix",
    graphrag_title: "GraphRAG Bilingual Intelligence Synthesis",
    mastermind_ranking: "Threat Mastermind Centrality Matrix",
    suspect_profile_title: "Conditional Suspect PII & Forensic Record",
    verify_confirm_identity: "VERIFY & CONFIRM IDENTITY (LOG AUDIT TRAIL)",
    dossier_title: "Final Comprehensive Police Intelligence Dossier",
    dispatch_matrix_title: "Tactical Dispatch & Intercept Protocol Matrix",
    export_pdf_btn: "EXPORT FORENSIC PDF (COMMANDER EXCLUSIVE)",
    logout: "Secure Logout",
    insights: "Crime Analytics Insights",
    my_account: "Officer Profile & Badge",
    settings: "Security & Zero-Trust Settings",
    onboarding: "Personnel Onboarding Request"
  },
  HI: {
    app_title: "नेत्रा-एआई - पुलिस इंटेलिजेंस सूट",
    commander_panel: "कमांडेंट केशव मुख्यालय पैनल",
    officer_workspace: "अधिकारी कार्यक्षेत्र",
    dashboard: "मुख्य जांच डैशबोर्ड",
    new_case_file: "नया केस दर्ज करें",
    search_cases_placeholder: "50+ मामलों को आईडी, शीर्षक या संदिग्ध के नाम से खोजें...",
    kpi_total: "कुल पंजीकृत मामले",
    kpi_solved: "सुलझाए गए मामलों की दर",
    kpi_pending: "सक्रिय लंबित मामले",
    kpi_efficiency: "जांच दक्षता दर",
    priority_critical: "अति संवेदनशील (क्रिटिकल)",
    priority_high: "उच्च प्राथमिकता",
    priority_medium: "मध्यम",
    status_pending: "जांच जारी / लंबित",
    status_completed: "सुलझाया गया / पूर्ण",
    evidence_grid_title: "मल्टी-मॉडल साक्ष्य संग्रहण ग्रिड",
    evidence_path_restricted: "स्थानीय सुरक्षित पथ: C:\\Users\\Keshav Kumawat\\Desktop\\sih 2026",
    batch_scan_btn: "सभी साक्ष्यों का एआई बैच स्कैन करें (YOLO, Face, NER)",
    graph_title: "नियो4जे लाइव ग्राफ एवं सिंडिकेट नेटवर्क",
    geospatial_title: "संदिग्ध का लाइव जीपीएस ट्रैकिंग मार्ग",
    xai_reasoning: "एक्सएआई (XAI) स्पष्टीकरण एवं साक्ष्य तर्क",
    graphrag_title: "ग्राफरैग (GraphRAG) द्विभाषी विश्लेषण",
    mastermind_ranking: "सिंडिकेट सरगना केंद्रीयता रैंकिंग",
    suspect_profile_title: "संदिग्ध व्यक्तिगत पहचान एवं विवरण",
    verify_confirm_identity: "पहचान सत्यापित एवं अनलॉक करें (ऑडिट लॉग)",
    dossier_title: "अंतिम पुलिस खुफिया रिपोर्ट (डॉजियर)",
    dispatch_matrix_title: "त्वरित पुलिस कार्रवाई एवं इंटरसेप्ट मैट्रिक्स",
    export_pdf_btn: "पीडीएफ रिपोर्ट डाउनलोड करें (केवल कमांडर)",
    logout: "सुरक्षित लॉगआउट",
    insights: "अपराध सांख्यिकी एवं चार्ट",
    my_account: "अधिकारी प्रोफ़ाइल",
    settings: "शून्य-विश्वास सुरक्षा नीतियां",
    onboarding: "नया अधिकारी पंजीकरण अनुरोध"
  },
  MR: {
    app_title: "नेत्रा-एआय - पोलिस गुप्तचर प्रणाली",
    commander_panel: "कमांडर केशव मुख्यालय पॅनेल",
    officer_workspace: "अधिकारी कार्यक्षेत्र",
    dashboard: "मुख्य तपास डॅशबोर्ड",
    new_case_file: "नवीन गुन्हा दाखल करा",
    search_cases_placeholder: "५०+ प्रकरणे आयडी किंवा संशयितावरून शोधा...",
    kpi_total: "एकूण नोंदवलेले गुन्हे",
    kpi_solved: "गुन्हे उकल प्रमाण",
    kpi_pending: "प्रलंबित तपास",
    kpi_efficiency: "तपास कार्यक्षमता",
    priority_critical: "अति महत्त्वाचे",
    priority_high: "उच्च",
    priority_medium: "मध्यम",
    status_pending: "तपास सुरू आहे",
    status_completed: "तपास पूर्ण / निकाली",
    evidence_grid_title: "पुरावे संकलन ग्रिड",
    evidence_path_restricted: "सुरक्षित मार्ग: C:\\Users\\Keshav Kumawat\\Desktop\\sih 2026",
    batch_scan_btn: "सर्व पुराव्यांचे एआय स्कॅन करा",
    graph_title: "नियो४जे नेटवर्क ग्राफ",
    geospatial_title: "थेट जीपीएस ट्रॅकिंग नकाशा",
    xai_reasoning: "तपास विश्लेषण तर्क",
    graphrag_title: "एआय विश्लेषक सारांश",
    mastermind_ranking: "टोळी प्रमुख क्रमवारी",
    suspect_profile_title: "संशयित व्यक्ती माहिती",
    verify_confirm_identity: "ओळख सत्यापित करा (ऑडिट लॉग)",
    dossier_title: "अंतिम गुप्तचर अहवाल",
    dispatch_matrix_title: "कारवाई आदेश मॅट्रिक्स",
    export_pdf_btn: "पीडीएफ अहवाल डाऊनलोड (केवळ कमांडर)",
    logout: "लॉगआउट",
    insights: "गुन्हे आकडेवारी",
    my_account: "अधिकारी खाते",
    settings: "सुरक्षा सेटिंग्ज",
    onboarding: "नवीन अधिकारी नोंदणी"
  },
  UR: {
    app_title: "نیترا اے آئی - پولیس انٹیلی جنس سوٹ",
    commander_panel: "کمانڈر کیشو ہیڈ کوارٹر پینل",
    officer_workspace: "افسر ورک اسپیس",
    dashboard: "مین انویسٹی گیشن ڈیش بورڈ",
    new_case_file: "نیا کیس درج کریں",
    search_cases_placeholder: "کیس تلاش کریں...",
    kpi_total: "کل درج شدہ کیسز",
    kpi_solved: "حل شدہ فیصد",
    kpi_pending: "زیر التوا کیسز",
    kpi_efficiency: "کارکردگی کی شرح",
    priority_critical: "انتہائی اہم",
    priority_high: "اعلیٰ",
    priority_medium: "درمیانہ",
    status_pending: "زیر تفتیش",
    status_completed: "مکمل شدہ",
    evidence_grid_title: "شواہد گرڈ",
    evidence_path_restricted: "مخصوص فولڈر: C:\\Users\\Keshav Kumawat\\Desktop\\sih 2026",
    batch_scan_btn: "تمام شواہد اسکین کریں",
    graph_title: "نیٹ ورک گراف",
    geospatial_title: "لائیو جی پی ایس ٹریکنگ",
    xai_reasoning: "تفتیشی دلائل",
    graphrag_title: "خلاصہ رپورٹ",
    mastermind_ranking: "مرکزی ملزمان کی فہرست",
    suspect_profile_title: "مشتبہ شخص کی تفصیلات",
    verify_confirm_identity: "شناخت کی تصدیق کریں",
    dossier_title: "حتمی انٹیلی جنس فائل",
    dispatch_matrix_title: "فوری ایکشن احکامات",
    export_pdf_btn: "پی ڈی ایف فائل ڈاؤن لوڈ (صرف کمانڈر)",
    logout: "لاگ آؤٹ",
    insights: "شماریات",
    my_account: "پروفائل",
    settings: "سیکیورٹی سیٹنگز",
    onboarding: "آن بورڈنگ درخواست"
  },
  PA: {
    app_title: "ਨੇਤਰਾ-ਏਆਈ - ਪੁਲਿਸ ਇੰਟੈਲੀਜੈਂਸ ਸੂਟ",
    commander_panel: "ਕਮਾਂਡਰ ਕੇਸ਼ਵ ਮੁੱਖ ਦਫ਼ਤਰ ਪੈਨਲ",
    officer_workspace: "ਅਫਸਰ ਵਰਕਸਪੇਸ",
    dashboard: "ਮੁੱਖ ਜਾਂਚ ਡੈਸ਼ਬੋਰਡ",
    new_case_file: "ਨਵਾਂ ਕੇਸ ਦਰਜ ਕਰੋ",
    search_cases_placeholder: "੫੦+ ਕੇਸਾਂ ਦੀ ਖੋਜ ਕਰੋ...",
    kpi_total: "ਕੁੱਲ ਦਰਜ ਕੇਸ",
    kpi_solved: "ਹੱਲ ਕੀਤੇ ਕੇਸਾਂ ਦੀ ਦਰ",
    kpi_pending: "ਬਕਾਇਆ ਕੇਸ",
    kpi_efficiency: "ਜਾਂਚ ਕੁਸ਼ਲਤਾ ਦਰ",
    priority_critical: "ਨਾਜ਼ੁਕ",
    priority_high: "ਉੱਚ",
    priority_medium: "ਦਰਮਿਆਨਾ",
    status_pending: "ਜਾਂਚ ਜਾਰੀ",
    status_completed: "ਸੁਲਝਾਇਆ ਗਿਆ",
    evidence_grid_title: "ਸਬੂਤ ਸੰਗ੍ਰਹਿ ਗਰਿੱਡ",
    evidence_path_restricted: "ਸੁਰੱਖਿਅਤ ਮਾਰਗ: C:\\Users\\Keshav Kumawat\\Desktop\\sih 2026",
    batch_scan_btn: "ਸਾਰੇ ਸਬੂਤ ਸਕੈਨ ਕਰੋ",
    graph_title: "ਨੈੱਟਵਰਕ ਗ੍ਰਾਫ",
    geospatial_title: "ਲਾਈਵ ਜੀਪੀਐਸ ਟਰੈਕਿੰਗ",
    xai_reasoning: "ਜਾਂਚ ਦਲੀਲਾਂ",
    graphrag_title: "ਖੁਫੀਆ ਸਾਰਾਂਸ਼",
    mastermind_ranking: "ਮੁੱਖ ਦੋਸ਼ੀ ਦਰਜਾਬੰਦੀ",
    suspect_profile_title: "ਸ਼ੱਕੀ ਵਿਅਕਤੀ ਦਾ ਵੇਰਵਾ",
    verify_confirm_identity: "ਪਛਾਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ (ਆਡਿਟ ਲੌਗ)",
    dossier_title: "ਅੰਤਿਮ ਪੁਲਿਸ ਰਿਪੋਰਟ",
    dispatch_matrix_title: "ਕਾਰਵਾਈ ਨਿਰਦੇਸ਼",
    export_pdf_btn: "ਪੀਡੀਐਫ ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ (ਸਿਰਫ ਕਮਾਂਡਰ)",
    logout: "ਲੌਗਆਊਟ",
    insights: "ਅਪਰਾਧ ਅੰਕੜੇ",
    my_account: "ਅਫਸਰ ਖਾਤਾ",
    settings: "ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ",
    onboarding: "ਨਵੇਂ ਅਫਸਰ ਦੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');
  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['EN']?.[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
